[[navbar]]
  identifier = "me"
  name = "Me"
  url = "/me/"
  weight = 1

  [[navbar]]
    identifier = "about"
    name = "About"
    url = "/me/about"
    parent = "me"
    weight = 1


  [[navbar]]
    identifier = "work"
    name = "Work"
    url = "/me/work"
    parent = "me"
    weight = 2

  [[navbar]]
    identifier = "projects"
    name = "Projects"
    url = "/me/projects"
    parent = "me"
    weight = 3

  [[navbar]]
    identifier = "connect"
    name = "Connect"
    url = "/me/connect"
    parent = "me"
    weight = 4

[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2